### ISSUE TITLE
Report problem with loading model in OpenSim Creator

### ISSUE THREAD

**Issue by itbellix** [imihasan/rmr-solver#1]
Hi @imihasan ,
I was trying to load your model with OpenSim Creator, but I have an error popping up:

![image](https://github.com/imihasan/rmr-solver/assets/50029203/2bd05804-3200-4d4f-a42f-3c6872890950)

It is probably related to the position in which the model is loaded by default, but looking at it in the OpenSim GUI I do not see anything strange happening for the left serratus anterior that is in the error. I am not sure what it is, I just wanted to report it as it could also be caused by something that will affect the RMR solver behaviour.
Did you ever see this before?

**Comment by imihasan** [comment]
Hi @itbellix;

That's because when the muscles of the left side were added, the ignore_tendon_compliance was not activated. To fix that, kindly activate that box from the properties window in Opensim GUI for the LSerrausAnterior_I and LSerrausAnterior_S muscles and save the model. You should be able then to open it in Opensim Creator.  If you leave the tendons of those muscles to be compliant, equilibrium cannot be computed given the current state. I believe that affects the behavior of the RMR because handling a compliant tendon would probably take more computational time. I will the rmr after modifying this and see if the computational performance improves. 

Let me know if it works and you can load the model now to OpenSim Creator.

**Comment by imihasan** [comment]
@itbellix I quickly checked and it sounds that this doesn't affect the solver speed as ignore_tendon_compliance is already set to true for all muscles in RMR_analysis.m
