### ISSUE TITLE
Visualizer doesn't work properly because some coordinates are dropped out of the optimization loop

### ISSUE THREAD

**Issue by imihasan** [imihasan/rmr-solver#6]

**Comment by imihasan** [comment]
@itbellix 

I think the issue is now solved and the states of all the coordinates are updated at each time instants. Now I think the visualization as well looks reasonable.

![image](https://github.com/imihasan/rmr-solver/assets/122603573/e111f7a3-cf69-4395-a797-b2311ab7df64)

I have pushed all the finals edits, kindly double check and let me know if you experience any issue.

**Comment by itbellix** [comment]
Nice @imihasan, thank you! I will check as soon as possible :)

**Comment by itbellix** [comment]
Hi @imihasan, I checked your modifications and they look alright to me, thank you!
I think above you sent a screenshot of wheelchair trial, not the `Upright_Lateral_Raise_90.trc`, right? Since on my computer I see the model standing and not sitting:
<img src="https://github.com/imihasan/rmr-solver/assets/50029203/a7eecfc7-c90c-42ae-883a-203e48a08a59" width=250>

**Comment by imihasan** [comment]
Hi @itbellix ,

Thanks for double checking! 
Yes indeed it's the same motion file. I just locked the hip angles at 60 flexion because I collected the data in a seated configuration. In your case I think the hip flexion angle was set to zero. So in both cases the model is sitting, but the hip flexion angle is different.
